### ISSUE TITLE
mp3tagsetup.exe not supported on this system

### ISSUE THREAD

**Issue by scottdk** [Xirg/docker-mp3tag#1]
I am trying to get this running in Docker on my QNAP NAS (_if relevant - TS-870 Pro upgraded with core-i7 and 16GB RAM_). It gets as far as the prompt to install **mono** which appears to succeed, then errors appear in the log. 

**I am getting this error in the logs :**
`04e0:err:process:exec_process L"Z:\\tmp\\mp3tagsetup.exe" not supported on this system`

It sounds like an issue with initialising the display due to X-Windows being missing on the host. (_This certainly looks to be the case in the test below with wordpad.exe._). 

Some other reading has suggested it's 32 bit vs 63 bit compatability, but I'm only guessing. And still suspect it's X Windows missing. 

**All I see in Guacamole in the browser or rdp is:**

   ![image](https://user-images.githubusercontent.com/11282782/126056381-add02047-d015-4c78-85e5-03039cf2cca2.png)

**Further testing with wordpad:**
`wine /config/.wine/drive_c/Program\ Files/Windows NT/Accessories/wordpad.exe`
The _"not supported on this system"_ error does not appear, but there is still no change in Guacamole to the earlier screenshot. Logs show:

`002c:fixme:winediag:LdrInitializeThunk wine-staging 6.3 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0024:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
0024:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet`

**I don't know if this is related, but an earlier error was:**
`Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
ERROR: openbox-xdg-autostart requires PyXDG to be installed`

I resolved this by running `apt-get update && apt-get install python-xdg` in the container's shell.

**docker-compose.yml**
[docker-compose.yml.txt](https://github.com/Xirg/docker-mp3tag/files/6835745/docker-compose.yml.txt)

**Container's Docker logs:**
[mp3tag-dockerlog.txt](https://github.com/Xirg/docker-mp3tag/files/6835692/mp3tag-dockerlog.txt)

**Processes running in the container:**
[processes.txt](https://github.com/Xirg/docker-mp3tag/files/6835687/processes.txt)

**EDIT:** 

**added docker-compose.yml**
[docker-compose.yml.txt](https://github.com/Xirg/docker-mp3tag/files/6835746/docker-compose.yml.txt)

**.env:**
```
UMASK=0002
PUID=1000
PGID=100
TZ=Australia/Melbourne
```

**Comment by gnuyen** [comment]
I also have this problem, just a black screen

**Comment by alekseyen** [comment]
same

**Comment by Xirg** [comment]
i tried adding the fix from 9Mad-Max5 -> https://github.com/9Mad-Max5/docker-mp3tag/commit/4d71c6b4329d848fd8339354d8194ccb0dda05cf
its untested as i dont have access to a QNAP nas

**Comment by madknave** [comment]
I know this has been closed, by I am still experiencing issues:
`002c:fixme:winediag:LdrInitializeThunk wine-staging 7.0-rc6 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0048:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0048:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0048:err:systray:initialize_systray Could not create tray window
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.`
